apiVersion: v1
#TODO: This should match the image tag and should be set using --app-version there's an open PR in helm to handle this
appVersion: "1.1.0"
description: A Helm chart for omantel-tomcat
name: omantel-tomcat
version: "1.0.0"
